# Generated by Django 2.0.7 on 2018-07-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('payee', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('REBI', 'Rent/Bills'), ('HSHD', 'Household'), ('TRVL', 'Travel'), ('GVNG', 'Giving'), ('FOOD', 'Food'), ('LESR', 'Leisure'), ('BOOK', 'Books'), ('SVGS', 'Savings'), ('OTHR', 'Other'), ('UNDF', 'Undefined (define later)')], default='UNDF', max_length=4)),
            ],
        ),
    ]
