# Generated by Django 2.0.7 on 2018-08-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label_short',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
