# Generated by Django 2.0.7 on 2018-08-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180829_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='inc_exp',
            field=models.BooleanField(default=False),
        ),
    ]
